@startuml

component "cli" {
}

component "common" {
}

component "formatter" {
}

component "interpreter" {
}

component "lexer" {
}

component "parser" {
}

component "sca" {
}

component "util" {
}

cli --> common
cli --> lexer
cli --> parser
cli --> interpreter
cli --> sca
cli --> formatter

formatter --> common

interpreter --> common

lexer --> common
lexer --> util

parser --> common

sca --> common

util --> common

@enduml